/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projetf1;

/**
 *
 * @author thoma
 */
public class MainFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    private F1Service service = new F1Service();

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();

        // On récupère les meetings 2023 via le service
        java.util.List<Meeting> meetings = service.fetchMeetings(2023);

// On crée un modèle pour la JList
        javax.swing.DefaultListModel model = new javax.swing.DefaultListModel();
        for (Meeting m : meetings) {
            model.addElement(m);
        }
        listMeetings.setModel(model); // Remplace 'listMeetings' par le nom que tu as donné à ta JList si différent
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        listMeetings = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDrivers = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblmeilleur_tour = new javax.swing.JLabel();
        lblvitesse_max = new javax.swing.JLabel();
        cbxannee = new javax.swing.JComboBox<>();
        lblSpeed = new javax.swing.JLabel();
        barRpm = new javax.swing.JProgressBar();
        lblDrs = new javax.swing.JLabel();
        circuitPanel = new com.mycompany.projetf1.TrackPanel();
        btnFavoris = new javax.swing.JButton();
        btnComparer = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listMeetings.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listMeetings.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listMeetingsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listMeetings);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Liste Des Grands Prix");

        tableDrivers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nom du Pilote", "N°", "Écurie "
            }
        ));
        tableDrivers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDriversMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableDrivers);

        txtSearch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtSearch.setToolTipText("Filtrer un pilote ");
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Pilote");

        lblmeilleur_tour.setText("meilleur tour :");

        lblvitesse_max.setText("vitesse Max :");

        cbxannee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2023", "2024", "2025", "2026" }));
        cbxannee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxanneeActionPerformed(evt);
            }
        });

        lblSpeed.setText("Vitesse Télémétrie : - km/h");

        barRpm.setMaximum(15000);
        barRpm.setToolTipText("");
        barRpm.setStringPainted(true);

        lblDrs.setText("DRS : -");

        javax.swing.GroupLayout circuitPanelLayout = new javax.swing.GroupLayout(circuitPanel);
        circuitPanel.setLayout(circuitPanelLayout);
        circuitPanelLayout.setHorizontalGroup(
            circuitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        circuitPanelLayout.setVerticalGroup(
            circuitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btnFavoris.setText("Ajouter aux favoris");
        btnFavoris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFavorisActionPerformed(evt);
            }
        });

        btnComparer.setText("Comparer à");
        btnComparer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComparerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbxannee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 319, Short.MAX_VALUE))
                    .addComponent(circuitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(barRpm, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDrs, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblmeilleur_tour, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblvitesse_max, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnFavoris)
                        .addGap(18, 18, 18)
                        .addComponent(btnComparer))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cbxannee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblmeilleur_tour)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblvitesse_max)
                                .addGap(23, 23, 23)
                                .addComponent(lblSpeed)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(barRpm, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(circuitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDrs)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFavoris)
                            .addComponent(btnComparer))
                        .addContainerGap(8, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        String search = txtSearch.getText().toLowerCase(); // Récupère ce que l'utilisateur a tapé
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tableDrivers.getModel();
        javax.swing.table.TableRowSorter<javax.swing.table.DefaultTableModel> sorter = new javax.swing.table.TableRowSorter<>(model);
        tableDrivers.setRowSorter(sorter);

// Applique le filtre sur la première colonne (le nom du pilote)
        sorter.setRowFilter(javax.swing.RowFilter.regexFilter("(?i)" + search, 0));
    }//GEN-LAST:event_txtSearchKeyReleased

    private void listMeetingsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listMeetingsValueChanged
        if (!evt.getValueIsAdjusting()) {
        Object selectedObj = listMeetings.getSelectedValue();
        
        if (selectedObj != null) {
            Meeting selected = (Meeting) selectedObj;
            
            try {
                // 1. Trouver la course (Race) de ce Grand Prix
                int sessionKey = service.fetchRaceSessionKey(selected.getMeetingKey());

                // 2. Télécharger les pilotes ET le classement de la course
                java.util.List<Driver> drivers = service.fetchDrivers(selected.getMeetingKey());
                java.util.List<SessionResult> results = service.fetchRaceResults(sessionKey);

                javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tableDrivers.getModel();
                model.setRowCount(0); // Vide le tableau

                if (results != null && !results.isEmpty()) {
                    // 3. On trie les résultats par position (du 1er au dernier)
                    results.sort((r1, r2) -> {
                        int pos1 = (r1.getPosition() != null) ? r1.getPosition() : 999;
                        int pos2 = (r2.getPosition() != null) ? r2.getPosition() : 999;
                        return Integer.compare(pos1, pos2);
                    });

                    // 4. On remplit le tableau dans l'ordre exact d'arrivée !
                    for (SessionResult result : results) {
                        if (result.getDriverNumber() != null) {
                            for (Driver d : drivers) {
                                if (String.valueOf(d.getDriverNumber()).equals(String.valueOf(result.getDriverNumber()))) {
                                    model.addRow(new Object[]{d.getFullName(), d.getDriverNumber(), d.getTeamName()});
                                    break;
                                }
                            }
                        }
                    }
                } else {
                    // SÉCURITÉ : Si la course n'a pas de classement (ex: essais)
                    java.util.HashSet<Integer> pilotesVus = new java.util.HashSet<>();
                    for (Driver d : drivers) {
                        if (!pilotesVus.contains(d.getDriverNumber())) {
                            pilotesVus.add(d.getDriverNumber());
                            model.addRow(new Object[]{d.getFullName(), d.getDriverNumber(), d.getTeamName()});
                        }
                    }
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
    }//GEN-LAST:event_listMeetingsValueChanged

    private void tableDriversMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDriversMouseClicked
        int viewRow = tableDrivers.getSelectedRow();

if (viewRow != -1) {
    int modelRow = tableDrivers.convertRowIndexToModel(viewRow);
    int driverNumber = (Integer) tableDrivers.getModel().getValueAt(modelRow, 1);
    
    // On garde la session 9157 (GP d'Italie) comme demandé dans la consigne
    // On récupère le Grand Prix que l'utilisateur a sélectionné à gauche
    Object selectedObj = listMeetings.getSelectedValue();
    Meeting selectedMeeting = (Meeting) selectedObj;
    int sessionKey = 9157; // Valeur de secours par défaut
    
    if (selectedMeeting != null) {
        // Le Moteur va chercher la vraie clé de la course pour CE Grand Prix précis !
        sessionKey = service.fetchRaceSessionKey(selectedMeeting.getMeetingKey());
    } 
    
    // ==========================================
    // VERSION 3 : LAPS (CHRONOS)
    // ==========================================
    java.util.List<Lap> laps = service.fetchLaps(sessionKey, driverNumber);
    Double bestLap = Double.MAX_VALUE; 
    Integer maxSpeed = 0;              
    
    for (Lap lap : laps) {
        if (lap.getLapDuration() != null && lap.getLapDuration() < bestLap) {
            bestLap = lap.getLapDuration();
        }
        if (lap.getStSpeed() != null && lap.getStSpeed() > maxSpeed) {
            maxSpeed = lap.getStSpeed();
        }
    }
    
    if (bestLap == Double.MAX_VALUE) {
        lblmeilleur_tour.setText("Meilleur tour : Aucun chrono");
    } else {
        lblmeilleur_tour.setText("Meilleur tour : " + bestLap + " s");
    }
    
    if (maxSpeed == 0) {
        lblvitesse_max.setText("Vitesse max : Inconnue");
    } else {
        lblvitesse_max.setText("Vitesse max : " + maxSpeed + " km/h");
    }

    // ==========================================
    // VERSION 4 : TELEMETRIE (VOITURE)
    // ==========================================
    java.util.List<CarData> telemetry = service.fetchCarData(sessionKey, driverNumber);
    
    if (!telemetry.isEmpty()) {
        // L'API renvoie des milliers de points. Pour le spectacle, 
        // on va chercher le moment exact où le pilote allait le plus vite !
        CarData topData = telemetry.get(0);
        for (CarData data : telemetry) {
            if (data.getSpeed() != null && topData.getSpeed() != null && data.getSpeed() > topData.getSpeed()) {
                topData = data;
            }
        }
        
        // 1. Mise à jour de la vitesse
        lblSpeed.setText("Vitesse Télémétrie : " + topData.getSpeed() + " km/h");
        
        // 2. Mise à jour du compte-tours (Jauge)
        if (topData.getRpm() != null) {
            barRpm.setValue(topData.getRpm());
            barRpm.setString(topData.getRpm() + " tr/min"); // Transforme le "0 %" en "12000 tr/min"
        }
        
        // 3. Mise à jour du DRS (Dans l'API, une valeur >= 8 veut dire aileron ouvert)
        if (topData.getDrs() != null && topData.getDrs() >= 8) {
            lblDrs.setText("DRS : Ouvert 🟩");
        } else {
            lblDrs.setText("DRS : Fermé 🟥");
        }
    } else {
        lblSpeed.setText("Vitesse Télémétrie : Aucune donnée");
        barRpm.setValue(0);
        barRpm.setString("0 tr/min");
        lblDrs.setText("DRS : -");
    }
    // ==========================================
    // VERSION 5 : DESSIN DU CIRCUIT
    // ==========================================
    java.util.List<Location> locations = service.fetchLocations(sessionKey, driverNumber);
    circuitPanel.setLocations(locations);
}
    }//GEN-LAST:event_tableDriversMouseClicked

    
    private void cbxanneeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxanneeActionPerformed
        // TODO add your handling code here:
        // 1. On récupère l'année sélectionnée dans la liste déroulante
int anneeSelectionnee = Integer.parseInt(cbxannee.getSelectedItem().toString());

// 2. On demande au service d'aller chercher les GP de cette année-là
java.util.List<Meeting> nouveauxMeetings = service.fetchMeetings(anneeSelectionnee);

// 3. On crée un nouveau modèle de liste tout neuf
javax.swing.DefaultListModel listModel = new javax.swing.DefaultListModel<>();

// 4. On le remplit avec les nouveaux GP
for (Meeting m : nouveauxMeetings) {
    listModel.addElement(m);
}

// 5. On met à jour la liste à l'écran
listMeetings.setModel(listModel);

// 6. Petit bonus : on vide le tableau des pilotes pour que ça reste propre !
javax.swing.table.DefaultTableModel tableModel = (javax.swing.table.DefaultTableModel) tableDrivers.getModel();
tableModel.setRowCount(0);
lblmeilleur_tour.setText("Meilleur tour : -");
lblvitesse_max.setText("Vitesse max : -");
    }//GEN-LAST:event_cbxanneeActionPerformed

    private void btnFavorisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFavorisActionPerformed
        // 1. On vérifie d'abord qu'un pilote est bien sélectionné dans le tableau
    int viewRow = tableDrivers.getSelectedRow();
    
    if (viewRow != -1) {
        // 2. On récupère les infos du tableau (Nom, Numéro, Ecurie)
        int modelRow = tableDrivers.convertRowIndexToModel(viewRow);
        
        // Attention : On suppose que la colonne 0 est le Nom, la 1 est le Numéro, la 2 est l'Écurie
        String nomPilote = tableDrivers.getModel().getValueAt(modelRow, 0).toString();
        String numPilote = tableDrivers.getModel().getValueAt(modelRow, 1).toString();
        String ecurie = tableDrivers.getModel().getValueAt(modelRow, 2).toString();
        
        // 3. On utilise FileWriter pour écrire dans un fichier "mes_favoris.txt"
        try {
            // Le "true" est très important : il permet d'ajouter à la suite du fichier sans écraser les précédents !
            java.io.FileWriter writer = new java.io.FileWriter("mes_favoris.txt", true); 
            writer.write("⭐ PILOTE FAVORI : " + nomPilote + " (N°" + numPilote + ") - " + ecurie + "\n");
            writer.close(); // Toujours fermer le fichier après écriture
            
            // 4. Petit message de confirmation visuel pour l'utilisateur
            javax.swing.JOptionPane.showMessageDialog(this, nomPilote + " a été sauvegardé dans tes favoris !");
            
        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Erreur lors de la sauvegarde.", "Erreur", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        
    } else {
        // Si l'utilisateur clique sur le bouton sans avoir cliqué sur le tableau d'abord
        javax.swing.JOptionPane.showMessageDialog(this, "Veuillez d'abord sélectionner un pilote dans le tableau !");
    }
    }//GEN-LAST:event_btnFavorisActionPerformed

    private void btnComparerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComparerActionPerformed
        // 1. On vérifie qu'un pilote (Pilote 1) est bien sélectionné
    int viewRow = tableDrivers.getSelectedRow();
    
    if (viewRow != -1) {
        int modelRow = tableDrivers.convertRowIndexToModel(viewRow);
        String nomPilote1 = tableDrivers.getModel().getValueAt(modelRow, 0).toString();
        int numPilote1 = (Integer) tableDrivers.getModel().getValueAt(modelRow, 1);
        
        // On récupère le Grand Prix actuel pour avoir la bonne session
        Object selectedObj = listMeetings.getSelectedValue();
        Meeting selectedMeeting = (Meeting) selectedObj;
        if (selectedMeeting == null) return;
        int sessionKey = service.fetchRaceSessionKey(selectedMeeting.getMeetingKey());

        // 2. On demande à l'utilisateur contre qui il veut comparer (Pilote 2)
        String input = javax.swing.JOptionPane.showInputDialog(this, 
                "Contre qui voulez-vous comparer " + nomPilote1 + " ?\nEntrez le NUMÉRO du 2ème pilote (ex: 44, 1, 16...) :");

        // Si l'utilisateur a tapé quelque chose et n'a pas annulé
        if (input != null && !input.trim().isEmpty()) {
            try {
                int numPilote2 = Integer.parseInt(input.trim());

                // 3. On télécharge les chronos des deux pilotes !
                java.util.List<Lap> laps1 = service.fetchLaps(sessionKey, numPilote1);
                java.util.List<Lap> laps2 = service.fetchLaps(sessionKey, numPilote2);

                // 4. On trouve le meilleur tour du Pilote 1
                Double bestLap1 = Double.MAX_VALUE;
                for (Lap lap : laps1) {
                    if (lap.getLapDuration() != null && lap.getLapDuration() < bestLap1) {
                        bestLap1 = lap.getLapDuration();
                    }
                }

                // 5. On trouve le meilleur tour du Pilote 2
                Double bestLap2 = Double.MAX_VALUE;
                for (Lap lap : laps2) {
                    if (lap.getLapDuration() != null && lap.getLapDuration() < bestLap2) {
                        bestLap2 = lap.getLapDuration();
                    }
                }

                // 6. On prépare l'affichage
                String txt1 = (bestLap1 == Double.MAX_VALUE) ? "Aucun temps" : bestLap1 + " s";
                String txt2 = (bestLap2 == Double.MAX_VALUE) ? "Aucun temps" : bestLap2 + " s";

                String vainqueur = "";
                if (bestLap1 < bestLap2) {
                    vainqueur = "🏆 Vainqueur : " + nomPilote1 + " !";
                } else if (bestLap2 < bestLap1) {
                    vainqueur = "🏆 Vainqueur : Pilote N°" + numPilote2 + " !";
                } else {
                    vainqueur = "🤝 Égalité ou données manquantes !";
                }

                // 7. On affiche le grand résultat final
                String message = "=== COMPARAISON DES MEILLEURS TOURS ===\n\n"
                               + "Pilote 1 (" + nomPilote1 + ") : " + txt1 + "\n"
                               + "Pilote 2 (N°" + numPilote2 + ") : " + txt2 + "\n\n"
                               + vainqueur;

                javax.swing.JOptionPane.showMessageDialog(this, message, "Résultat du Duel", javax.swing.JOptionPane.INFORMATION_MESSAGE);

            } catch (NumberFormatException e) {
                // Sécurité au cas où l'utilisateur tape des lettres au lieu d'un numéro
                javax.swing.JOptionPane.showMessageDialog(this, "Veuillez entrer un numéro de pilote valide (chiffres uniquement).", "Erreur", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Veuillez d'abord sélectionner le Pilote 1 dans le tableau !");
    }   
    }//GEN-LAST:event_btnComparerActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barRpm;
    private javax.swing.JButton btnComparer;
    private javax.swing.JButton btnFavoris;
    private javax.swing.JComboBox<String> cbxannee;
    private com.mycompany.projetf1.TrackPanel circuitPanel;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDrs;
    private javax.swing.JLabel lblSpeed;
    private javax.swing.JLabel lblmeilleur_tour;
    private javax.swing.JLabel lblvitesse_max;
    private javax.swing.JList<String> listMeetings;
    private javax.swing.JTable tableDrivers;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
